server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    undertow:
      threads:
        worker: 64
        io: 4

spring:
  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.database}
    username: ${postgres.username}
    password: ${postgres.password}

  jpa:
    properties:
      hibernate:
        dialect: ${postgres.dialect}