postgres:
  username: docker
  password: docker
  url: localhost:5432
  dialect: org.hibernate.dialect.PostgreSQLDialect
  database: tech_events

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2